# Development Configuration
spring.config.activate.on-profile=dev

# Database (Local)
spring.datasource.url=jdbc:mysql://localhost:3306/cryptonex?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Shiv@m568684
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Debugging
logging.level.com.cryptonex=DEBUG
logging.level.org.springframework.security=DEBUG
